title: Ari Wigdorowitz
url: "https://"
baseurl: "/cv"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: " https://wigdo.github.io/papyrus"
footer_text: "Check out my blog"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Download this CV"
   link: "resume.pdf"
 - name: "Contact me"
   link: "contact"
